build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.11"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "nanomsg/1.0.0"
    CONAN_USERNAME: "Wi3ard"
    CONAN_CHANNEL: "stable"
    CONAN_TOTAL_PAGES: 4

    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4

init:
    - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
    - set PATH=%PATH%;%PYTHON%/Scripts/
    - pip.exe install conan_package_tools # This installs conan too
    - conan user # This creates the conan data directory

test_script:
    - python build.py
